accessControl:
  userfile: /octoprint/octoprint/users.yaml
plugins:
  fractalbridge:
    token: 
  tracking:
    enabled: false
  virtual_printer:
    _config_version: 1
    enabled: true
printerProfiles:
  default: _default
server:
  firstRun: false
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: true
  commands:
    serverRestartCommand: s6-svc -r /var/run/s6/services/octoprint
webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream